### ISSUE TITLE
Feature Request: Alert suspension of posting generated by warning system

### ISSUE THREAD

**Issue by martec** [MyAlerts/Moderation-Alerts-Pack#13]
http://i.imgur.com/zqd4NRn.png

Generate alert when warning system suspend post privileges.

http://community.mybb.com/thread-131176-post-1024027.html#pid1024027
http://community.mybb.com/thread-131176-post-1024030.html#pid1024030

**Comment by Shade-** [comment]
This should be handled already thanks to the $plugins object which has been instantiated in MyBB 1.8.
