### ISSUE TITLE
Broken if you Stick any Thread.

### ISSUE THREAD

**Issue by MrCraigTunstall** [MyAlerts/Moderation-Alerts-Pack#17]
Fatal error: Call to undefined function myalertsmore_addAlert_stick_thread() in /home/voidreso/public_html/inc/class_plugins.php on line 139

**Comment by ozanakkaya** [comment]
hi.
myalertsmore.php line 530

$plugins->add_hook('class_moderation_stick_threads', 'myalertsmore_addAlert_stick_thread');

replace

$plugins->add_hook('class_moderation_stick_threads', 'myalertsmore_addAlert_stick_threads');

**Comment by Shade-** [comment]
Thank you for your contribution. I don't have much spare time so if you could create a new PR it would be awesome.

**Comment by Shade-** [comment]
3 years have passed, but this issue has been solved long time ago with v4.0.
