### ISSUE TITLE
Move Threads, forum name is null

### ISSUE THREAD

**Issue by ozanakkaya** [MyAlerts/Moderation-Alerts-Pack#18]
move threads, forum name is null,

**'destination_name' => $forum['name']** not work.

**Comment by Shade-** [comment]
Thank you for your contribution. Please read #17

**Comment by ozanakkaya** [comment]
Hi shade,

myalertsmore.php line 180,181

```
			'search' => '$arguments = array("tids" => $tids, "moveto" => $moveto);',
			'after' => '$arguments["newforum"] = &$newforum;'
```

replace

```
			'search' => '$args = array("tids" => $tids, "moveto" => $moveto);',
			'after' => '$args["newforum"] = &$newforum;'
```


Line 387 

		`$forum = get_forum($args['new_tid']);`

replace

		`$forum = get_forum($args['new_fid']);`
